SportsStore.WebUI/Models/CartIndexViewModel.cs
using SportsStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SportsStore.WebUI.Models
{
	public class CartIndexViewModel
	{
		public Cart Cart { get; set; }
		public string ReturnUrl { get; set; }
	}
}

SportsStore.WebUI/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SportsStore.WebUI.Models
{
	public class LoginViewModel
	{
		[Required]
		public string UserName { get; set; }
		[Required]
		[DataType(DataType.Password)]
		public string Password { get; set; }
	}
}

SportsStore.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SportsStore.WebUI.Models
{
	public class PagingInfo
	{
		public int TotalItems { get; set; }
		public int ItemsPerPage { get; set; }
		public int CurrentPage { get; set; }

		public int TotalPages
		{
			get { return (int) Math.Ceiling((decimal) TotalItems / ItemsPerPage); }
		}
	}
}

SportsStore.WebUI/Models/ProductsListViewModel.cs
using SportsStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SportsStore.WebUI.Models
{
	public class ProductsListViewModel
	{
		public IEnumerable<Product> Products { get; set; }
		public PagingInfo PagingInfo { get; set; }
		public string CurrentCategory { get; set; }
	}
}

SportsStore.WebUI/Controllers/AccountController.cs
using System.Web.Mvc;
using SportsStore.WebUI.Infrastructure.Abstract;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
	public class AccountController : Controller
	{
		IAuthProvider authProvider;
		public AccountController (IAuthProvider auth)
		{
			authProvider = auth;
		}
		public ViewResult Login ()
		{
			return View();
		}
		[HttpPost]
		public ActionResult Login (LoginViewModel model, string returnUrl)
		{
			if (ModelState.IsValid)
			{
				if (authProvider.Authenticate(model.UserName, model.Password))
				{
					return Redirect(returnUrl ?? Url.Action("Index", "Admin"));
				}
				else
				{
					ModelState.AddModelError("", "Incorrect username or password");
					return View();
				}
			}
			else
			{
				return View();
			}
		}
	}
}

SportsStore.WebUI/Controllers/AdminController.cs
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
	[Authorize]
    public class AdminController : Controller
    {
		private IProductRepository repository;

		public AdminController (IProductRepository repo)
		{
			repository = repo;
		}

		public ViewResult Index ()
		{
			return View(repository.Products);
		}

		public ViewResult Edit (int productId)
		{
			Product product = repository.Products
			  .FirstOrDefault(p => p.ProductID == productId);
			return View(product);
		}

		[HttpPost]
		public ActionResult Edit (Product product, HttpPostedFileBase image)
		{
			if (ModelState.IsValid)
			{
				if (image != null)
				{
					product.ImageMimeType = image.ContentType;
					product.ImageData = new byte[image.ContentLength];
					image.InputStream.Read(product.ImageData, 0, image.ContentLength);
				}

				repository.SaveProduct(product);
				TempData["message"] = string.Format("{0} has been saved", product.Name);
				return RedirectToAction("Index");
			}
			else
			{
				// there is something wrong with the data values
				return View(product);
			}
		}

		public ViewResult Create ()
		{
			return View("Edit", new Product());
		}

		[HttpPost]
		public ActionResult Delete (int productId)
		{
			Product deletedProduct = repository.DeleteProduct(productId);
			if (deletedProduct != null)
			{
				TempData["message"] = string.Format("{0} was deleted", deletedProduct.Name);
			}
			return RedirectToAction("Index");
		}
    }
}

SportsStore.WebUI/Controllers/CartController.cs
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    public class CartController : Controller
    {
		private IProductRepository repository;
		private IOrderProcessor orderProcessor;

		public CartController (IProductRepository repo, IOrderProcessor proc)
		{
			repository = repo;
			orderProcessor = proc;
		}

		public ViewResult Index (Cart cart, string returnUrl)
		{
			return View(new CartIndexViewModel
			{
				Cart = cart,
				ReturnUrl = returnUrl
			});
		}

		public RedirectToRouteResult AddToCart (Cart cart, int productId, string returnUrl)
		{
			Product product = repository.Products
			.FirstOrDefault(p => p.ProductID == productId);
			if (product != null)
			{
				cart.AddItem(product, 1);
			}
			return RedirectToAction("Index", new { returnUrl });
		}

		public RedirectToRouteResult RemoveFromCart (Cart cart, int productId, string returnUrl)
		{
			Product product = repository.Products
			.FirstOrDefault(p => p.ProductID == productId);
			if (product != null)
			{
				cart.RemoveLine(product);
			}
			return RedirectToAction("Index", new { returnUrl });
		}

		public PartialViewResult Summary (Cart cart)
		{
			return PartialView(cart);
		}

		[HttpPost]
		public ViewResult Checkout (Cart cart, ShippingDetails shippingDetails)
		{
			if (cart.Lines.Count() == 0)
			{
				ModelState.AddModelError("", "Sorry, your cart is empty!");
			}
			if (ModelState.IsValid)
			{
				orderProcessor.ProcessOrder(cart, shippingDetails);
				cart.Clear();
				return View("Completed");
			}
			else
			{
				return View(shippingDetails);
			}
		}

		public ViewResult Checkout ()
		{
			return View(new ShippingDetails());
		}

		//private Cart GetCart ()
		//{
		//	Cart cart = (Cart) Session["Cart"];
		//	if (cart == null)
		//	{
		//		cart = new Cart();
		//		Session["Cart"] = cart;
		//	}
		//	return cart;
		//}

    }
}

SportsStore.WebUI/Controllers/NavController.cs
using SportsStore.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    public class NavController : Controller
    {
		private IProductRepository repository;

		public NavController (IProductRepository repo)
		{
			repository = repo;
		}

		public PartialViewResult Menu (string category=null)
		{
			ViewBag.SelectedCategory = category;
			IEnumerable<string> categories = repository.Products
			  .Select(x => x.Category)
			  .Distinct()
			  .OrderBy(x => x);
			return PartialView(categories);
		}
    }
}

SportsStore.WebUI/Controllers/ProductController.cs
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
		private IProductRepository repository;
		public int PageSize = 4;
		public ProductController (IProductRepository productRepository)
		{
			this.repository = productRepository;
		}
		public ViewResult List (string category, int page = 1)
		{
			ProductsListViewModel model = new ProductsListViewModel
			{
				Products = repository.Products
					.Where(p=>category==null || p.Category==category)
					.OrderBy(p => p.ProductID)
					.Skip((page - 1) * PageSize)
					.Take(PageSize),
				PagingInfo = new PagingInfo
				{
					CurrentPage = page,
					ItemsPerPage = PageSize,
					TotalItems = category == null ?
						repository.Products.Count() :
						repository.Products.Where(e => e.Category == category).Count()
				},
				CurrentCategory=category
			};

			return View(model);
		}

		public FileContentResult GetImage (int productId)
		{
			Product prod = repository.Products.FirstOrDefault(p => p.ProductID == productId);
			if (prod != null)
			{
				return File(prod.ImageData, prod.ImageMimeType);
			}
			else
			{
				return null;
			}
		}
    }
}

SportsStore.WebUI/Views/Admin/Edit.cshtml
@model SportsStore.Domain.Entities.Product

@{
	ViewBag.Title = "Edit";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
	<h1>Edit @Model.Name</h1>
	<div class="form-group">
		@using (Html.BeginForm("Edit", "Admin",
		FormMethod.Post, new { enctype = "multipart/form-data" }))
  {
			@Html.EditorForModel()
			<div class="editor-label">Image</div>
			<div class="editor-field">
				@if (Model.ImageData == null)
	{
					@:None
    }
	else
	{
					<img width="150" height="150" src="@Url.Action("GetImage", "Product", new { Model.ProductID })" />
	}
				<div>
					Upload new image:
      <input type="file" name="Image" />
				</div>
			</div>
			<input type="submit" value="Save" class="btn btn-default" />
			@Html.ActionLink("Cancel and return to List", "Index")
  }
	</div>
</div>

SportsStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<SportsStore.Domain.Entities.Product>

@{
	ViewBag.Title = "Admin: All Products";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
	<h1>All Products</h1>
	<table class="table">
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th class="NumericCol">Price</th>
			<th>Actions</th>
		</tr>
		@foreach (var item in Model)
  {
			<tr>
				<td>@item.ProductID</td>
				<td>@Html.ActionLink(item.Name, "Edit", new { item.ProductID })</td>
				<td class="NumericCol">@item.Price.ToString("c")</td>
				<td>
					@using (Html.BeginForm("Delete", "Admin"))
	 {
						@Html.Hidden("ProductID", item.ProductID)
						<input type="submit" value="Delete" class="btn btn-default" />
	 }
				</td>
			</tr>
  }
	</table>
	<p>@Html.ActionLink("Add a new product", "Create")</p>
</div>

SportsStore.WebUI/Views/Cart/Checkout.cshtml
@model SportsStore.Domain.Entities.ShippingDetails

@{
  ViewBag.Title = "SportStore: Checkout";
}

<h2>Check out now</h2>
Please enter your details, and we'll ship your goods right away!
@using (Html.BeginForm())
{
  @Html.ValidationSummary()
  <h3>Ship to</h3>
  <div>Name: @Html.EditorFor(x => x.Name)</div>
  <h3>Address</h3>
  <div>Line 1: @Html.EditorFor(x => x.Line1)</div>
  <div>Line 2: @Html.EditorFor(x => x.Line2)</div>
  <div>Line 3: @Html.EditorFor(x => x.Line3)</div>
  <div>City: @Html.EditorFor(x => x.City)</div>
  <div>State: @Html.EditorFor(x => x.State)</div>
  <div>Zip: @Html.EditorFor(x => x.Zip)</div>
  <div>Country: @Html.EditorFor(x => x.Country)</div>
  <h3>Options</h3>
  <label>
    @Html.EditorFor(x => x.GiftWrap)
    Gift wrap these items
  </label>
  
  <p align="center">
    <input class="btn btn-success" type="submit" value="Complete order" />
  </p>
}

SportsStore.WebUI/Views/Cart/Completed.cshtml
@{
  ViewBag.Title = "SportsStore: Order Submitted";
}

<h2>Thanks!</h2>
Thanks for placing your order. We'll ship your goods as soon as possible.

SportsStore.WebUI/Views/Cart/Index.cshtml
@model SportsStore.WebUI.Models.CartIndexViewModel

@{
  ViewBag.Title = "Sports Store: Your Cart";
}

<h2>Your cart</h2>
<table class="table  table-striped table-bordered">
  <thead>
    <tr>
      <th align="center">Quantity</th>
      <th align="left">Item</th>
      <th align="right">Price</th>
      <th align="right">Subtotal</th>
    </tr>
  </thead>
  <tbody>
    @foreach (var line in Model.Cart.Lines) {
      <tr>
        <td>@line.Quantity</td>
        <td>@line.Product.Name</td>
        <td>@line.Product.Price.ToString("c")</td>
        <td>@((line.Quantity * line.Product.Price).ToString("c"))</td>
		<td>
			@using (Html.BeginForm("RemoveFromCart", "Cart")) {
			  @Html.Hidden("ProductId", line.Product.ProductID)
			  @Html.HiddenFor(x => x.ReturnUrl)
			  <input class="btn btn-default" type="submit" value="Remove" />
        }
      </td>
      </tr>
    }
  </tbody>
  <tfoot>
    <tr  class="success">
      <td colspan="3">Total:</td>
      <td>
        @Model.Cart.ComputeTotalValue().ToString("c")
      </td>
    </tr>
  </tfoot>
</table>
<div>
  <a class="btn btn-default" href="@Model.ReturnUrl">Continue shopping</a>

  @Html.ActionLink("Checkout now", "Checkout", new { Class = "btn btn-primary" })
</div>

SportsStore.WebUI/Views/Cart/Summary.cshtml
@model SportsStore.Domain.Entities.Cart

<div id="cart">
  <span class="caption">
    <b>Your cart:</b>
    @Model.Lines.Sum(x => x.Quantity) item(s),
    @Model.ComputeTotalValue().ToString("c")
  </span>

  @Html.ActionLink("Checkout", "Index", "Cart", new { returnUrl = Request.Url.PathAndQuery }, new { Class = "btn btn-default" })
</div>

SportsStore.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Home", "List", "Product")

@foreach (var link in Model)
{
	@Html.RouteLink(link, new
	{
		controller = "Product",
		action = "List",
		category = link,
		page = 1
	},
	  new
	  {
		  @class = link == ViewBag.SelectedCategory ? "selected" : null
	  })
}

SportsStore.WebUI/Views/Product/List.cshtml
@model SportsStore.WebUI.Models.ProductsListViewModel

@{
	ViewBag.Title = "Products";
}

@foreach (var p in Model.Products)
{
	Html.RenderPartial("ProductSummary", p);
}

<ul class="pagination">
  @Html.PageLinks(Model.PagingInfo, x => Url.Action("List",
    new { page = x, category = Model.CurrentCategory }))
</ul>

SportsStore.WebUI/Views/Shared/ProductSummary.cshtml
@model SportsStore.Domain.Entities.Product

<div class="row">

	<div class="col-md-11">
		<h4>@Model.Name</h4>
		
			 @if (Model.ImageData != null) {
    <div style="float: left; margin-right: 20px">
      <img width="75" height="75" src="@Url.Action("GetImage", "Product", new { Model.ProductID })" />
    </div>
  }
		@Model.Description
		@Model.Price.ToString("c")
	</div>
	<div class="col-md-1">
		@using (Html.BeginForm("AddToCart", "Cart"))
		{
			@Html.HiddenFor(x => x.ProductID)
			@Html.Hidden("returnUrl", Request.Url.PathAndQuery)
			<input type="submit" class="btn btn-primary" value="+ Add to cart" />
		}
	</div>


</div>

SportsStore.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<link href="~/Content/Admin.css" rel="stylesheet" type="text/css" />
	<link href="~/Content/bootstrap/bootstrap.min.css" rel="stylesheet">
	<script src="~/Scripts/jquery-1.8.2.js"></script>
	<script src="~/Scripts/jquery.validate.min.js"></script>
	<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

	<title></title>
</head>
<body>
	<div>
		@if (TempData["message"] != null)
  {
			<div class="Message">@TempData["message"]</div>
  }
		@RenderBody()
	</div>
</body>
</html>

SportsStore.WebUI/Views/Shared/_Layout.cshtml
@*<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>*@
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<title>@ViewBag.Title</title>
	<link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
	<link href="~/Content/bootstrap/bootstrap.min.css" rel="stylesheet">
</head>
<body>
	<script src="~/Content/bootstrap.min.js"></script>
	<script src="~/Content/jquery-1.8.2.min.js"></script>


	<div id="header">
		@{Html.RenderAction("Summary", "Cart");}
		<div class="title">SPORTS STORE</div>
	</div>
	<div id="categories">
		@{ Html.RenderAction("Menu", "Nav"); }
	</div>
	<div id="content">
		@RenderBody()
	</div>

</body>
</html>